### ISSUE TITLE
BUG: docker compose not working

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#282]
```
whist-server  | Traceback (most recent call last):
whist-server  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
whist-server  |     return _run_code(code, main_globals, None,
whist-server  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
whist-server  |     exec(code, run_globals)
whist-server  |   File "//whist/server/__main__.py", line 4, in <module>
whist-server  |     from whist.server.cli import main
whist-server  |   File "/whist/server/__init__.py", line 38, in <module>
whist-server  |     version = pkg_resources.get_distribution(module).version
whist-server  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 466, in get_distribution
whist-server  |     dist = get_provider(dist)
whist-server  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 342, in get_provider
whist-server  |     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
whist-server  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
whist-server  |     needed = self.resolve(parse_requirements(requirements))
whist-server  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
whist-server  |     raise DistributionNotFound(req, requirers)
whist-server  | pkg_resources.DistributionNotFound: The 'whist-server' distribution was not found and is required by the application
whist-server exited with code 1
```
Docker compose Raspberry 4 with ubuntu 21.04 server edition.

```yml
version: '3'
services:
  web:
    container_name: whist-server
    image: teamwhist/whist-server:arm64-latest
    ports:
      - "9001:8080"
    depends_on:
      - mongo
    restart: always
    environment:
      DATABASE_NAME: mongo
  mongo:
    container_name: mongodb
    image: mongo:4.4
```

EDIT: reproducible with ubuntu 20.04 on amd64
